In [4]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print("z ",z)
print("############")
v = torch.tensor([0.1,1.0, 0.001], dtype=torch.float32)
print("v ",v)
z.backward() #dz/dx
print("z ",z)
print("x ",x.grad)


############# autograd demo
second = torch.tensor([2.0], requires_grad=True)
first = second**2
first.backward()
print(second.grad)

tensor([-0.2381,  0.7982, -0.8911], requires_grad=True)
tensor([1.7619, 2.7982, 1.1089], grad_fn=<AddBackward0>)
z  tensor(8.1090, grad_fn=<MeanBackward0>)
############
v  tensor([0.1000, 1.0000, 0.0010])
z  tensor(8.1090, grad_fn=<MeanBackward0>)
x  tensor([2.3492, 3.7309, 1.4785])
tensor([4.])
