In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Dummy input: batch of 4 samples, each of size 5 (like a "feature vector")
x = torch.randn(4,5) # shape = (batch_size=4, input_dim=5)

# Dummy labels: correct class for each sample (must be in 0,1,2)
y = torch.tensor([0,2,1,0]) # shape = (4,) Integers only for CrossEntropyLoss

# Define a simple model
class TinyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(5,6)  # 5 -> 6 hidden units
        self.fc2 = nn.Linear(6,3)  # 6 -> 3 output units

    def forward(self,x):
        x = F.relu(self.fc1(x)) # Apply ReLU activation
        return self.fc2(x) # Raw logits (no softmax)

model = TinyModel()

# Forward pass
logits = model(x) # shape = (4,3) -> 4 samples, 3 class scores each
print("Logits shape:\n", logits)


# Predict class
predicted_class = torch.argmax(logits, dim=1) # shape = (4,) -> 4 samples, 1 class score each
print(f"\nPredicted class:\n{predicted_class}")
print("Actual class:\n", y)

Logits shape:
 tensor([[ 0.1499, -0.6248, -0.3016],
        [ 0.2706, -0.3590, -0.7536],
        [ 0.3162, -0.5984, -0.3426],
        [ 0.1718, -0.2973, -0.7576]], grad_fn=<AddmmBackward0>)

Predicted class:
tensor([0, 0, 0, 0])
Actual class:
 tensor([0, 2, 1, 0])


In [2]:
import os

data_dir = "data/fashion-mnist"

#Create directory if it doesn't exist
os.makedirs(data_dir, exist_ok=True)